FROM node:fermium-alpine

ARG NETWORK=bsc
ENV NETWORK ${NETWORK}
ARG NETWORK_FILE="./contracts/networks.json"
ENV NETWORK_FILE ${NETWORK_FILE}

RUN apk add git

RUN mkdir -p /opt/app
WORKDIR /opt/app
COPY package.json ./
COPY yarn.lock ./
RUN yarn --frozen-lockfile

COPY . .
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait
RUN chmod +x /wait

CMD [ "sh", "-c", "/wait && yarn clean && yarn codegen && yarn create:env && yarn deploy:env" ]
